Repository Kharacternyk/pacwall, pull requests merged in 2020-03, with the labels that each got.

#7 Change bg in gnome
  pacwall.sh
Labels: bug

#1 Automatically get screensize, using xpdyinfo
  pacwall.sh
Labels: enhancement

#2 Use tempdir and copy result to pwd
  pacwall.sh
Labels: enhancement

#3 Add PKGBUILD
  .gitignore
  PKGBUILD-git
  README.rst
  pacwall.sh
Labels: AUR, enhancement

#13 Write output to XDG dir and write XML for GNOME
  pacwall.sh
Labels: GNOME, enhancement

#15 debtree support (Debian, Ubuntu, Mint, Pop_OS!, ...).
  pacwall.sh
Labels: debtree, enhancement

#23 Fix typo, add feh to DE mode, update README
  README.rst
  pacwall.sh
Labels: DE, bug, documentation, enhancement
